### ISSUE TITLE
Trouble installing dependancies

### ISSUE THREAD

**Issue by danrossi** [Orange-OpenSource/hasplayer.js#105]
There seems to be alot of broken packages using older grunt version dependancies. On many packages but this for example is stuck in a loop trying to build native bindings for osx. 

```
gyp ERR! not ok 
npm ERR! addLocal Could not install /hasplayer/build/xo@*
npm WARN package.json Dependency 'shelljs' exists in both dependencies and devDependencies, using 'shelljs@0.1.x' from dependencies
npm WARN package.json Dependency 'shelljs' exists in both dependencies and devDependencies, using 'shelljs@0.1.x' from dependencies
npm WARN package.json Dependency 'shelljs' exists in both dependencies and devDependencies, using 'shelljs@0.1.x' from dependencies
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm WARN package.json Dependency 'shelljs' exists in both dependencies and devDependencies, using 'shelljs@0.1.x' from dependencies
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.4.2","npm":"2.15.2"})
 
> buffertools@2.1.4 install /hasplayer/build/node_modules/grunt-load-options/node_modules/load-grunt-tasks/node_modules/minimatch/node_modules/tap/node_modules/deeper/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/buffertools.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /hasplayer/build/node_modules/grunt-load-options/node_modules/load-grunt-tasks/node_modules/minimatch/node_modules/tap/node_modules/deeper/node_modules/buffertools
```

I tried all kinds of things including manually installing one by one but meet similar errors with another package ie grunt-css-url-embed. 

It does not install out of the box. I also have to run it as

```
npm install -dev
```

Any ideas ?

**Comment by bbert** [comment]
FYI, we are replacing grunt by gulp and will deliver it very soon.
Maybe that will resolve your issue.

**Comment by bbert** [comment]
Hi,
Development branch has been updated with gulp building.
Please be also aware of MediaPlayer API refactoring. (see #111)

**Comment by danrossi** [comment]
It has apparently built thanks. 

Doing this 

```
cd build
gulp
```
